### ISSUE TITLE
Selected more items with shift key

### ISSUE THREAD

**Issue by LolBruflex** [d3lm/ngx-drag-to-select#87] opened 2019-09-26 15:55 UTC
Hello and congratulations for this wonderful app!
a question, is it possible to select several consecutive elements, selecting the first one, keeping the shift key pressed, and clicking on a subsequent element? like the classic selection of multiple files on the window with the shift key!

thanks

**Comment by d3lm** [comment] 2019-09-26 16:24
Hey there! Thanks, glad you like it. This feature is not yet supported but was already requested in #79. We have to figure out which key we can reuse of if this is a mode you have to enable, because `shift` is already used for adding items to the current selection. I am open to discuss this and implement this feature. I think it's very useful and it seems people want this.

I am closing this one because it's a duplicate of #79. Let's move this discussion over to the existing issue.

**Closed by d3lm** 2019-09-26 16:24 UTC
