### ISSUE TITLE
Bounding box and resize bug

### ISSUE THREAD

**Issue by toddhd** [d3lm/ngx-drag-to-select#68] opened 2018-12-30 19:56 UTC
I see there are a few issues related to this but since I'm seeing still, I figured I'd mention it. Please see the video for a demo and explanation. https://www.youtube.com/watch?v=BVthAyI8eYs

In a nutshell, when I first open the web page, the Bounding box is way off... it doesn't show up where I'm clicking and dragging. Doing anything that causes a resize (e.g. resize the window, press F12 to open the dev tools) "fixes" it.

**Comment by d3lm** [comment] 2018-12-31 08:06
Thanks Todd, for filing this issue. I am really happy that you're testing this lib extensively.

I have quickly tried to reproduce this on my machine (Mac, Firefox) but I can't really see the issue in action. Do you mind creating a minimal reproducable, like a [StackBlitz](https://stackblitz.com/) that shows the issue? From there I can then debug the problem and see what's causing it.

**Comment by timdeschryver** [comment] 2019-01-02 19:43
@toddhd do you load in the data in an `async` way, or is it all static data?
You could try calling the `update` method when you've rendered the data, this will do some re-calculations on the bounding box for the container and its children.

You can take a look at the `Public Methods` section in the README for an example.

**Comment by toddhd** [comment] 2019-01-02 20:15
Thank you Dominic. I've been unable to reproduce this bug on say,
StackBlitz, but can reproduce it locally consistently. I was able to force
my page to call the Resize() event in the meantime which fixes it, but I
will look at the update method you suggested. The data is static.

**Comment by d3lm** [comment] 2019-01-03 10:33
Ok, I am wondering what's causing this "issue" for you locally. I am curious to find out what it is but it's pretty difficult to do so without a working example, or a setup that is causing this.

But try to all `update` on the `select-container` once your items have been loaded. Still, it's pretty weird that this only occurs in Firefox and in Chrome everything seems to work just fine... 🤔

**Comment by toddhd** [comment] 2019-01-17 19:38
https://www.youtube.com/watch?v=59FxIGtvpMI

Hi - sorry to be that "naggy" guy, but I'm still having some weird issues.
For what it's worth I am willing to share this demo code on GItHub with
you, but would prefer to not the URL out over a public forum like this. One
thing I forgot to mention, and maybe it is relevant, is that I am
"reselecting" some areas by selecting over them. Maybe that's the problem?
I'll make a video of that as well for you.

**Comment by toddhd** [comment] 2019-01-17 19:47
https://youtu.be/zKdfhff6EtE

**Comment by d3lm** [comment] 2019-01-18 07:32
Thanks again for the great explanations, Todd. You don't have to be sorry for opening and posting updates on this issue. I really want to improve this library and iron out any bugs that make this lib less usable. So keep on doing this! The only expecation I have for people that file issues is to also invest some effort in trying to reproduce it. But you clearly do that and you even record videos to demonstrate the issue. So thanks a lot for that. Those will be helpful for me once I can debug the problem.

Can you reproduce this in a very minimal Angular project created by the CLI? You don't have to necessarily use StackBlitz to reproduce the issue. You can also create a new project locally and push this into a repo on Github. As long as I have some minimal project that shows the issue, I have everything I need to fix it.

But normally that "reselecting" should work just fine. I have e2e tests that verify its functionality but of course that doesn't mean there are no bugs. It could be that I missed something.

So my suggestion would be that you try to reproduce this in a minimal CLI project and push it into a GitHub repo. If that doesn't work, you can give me access to your project and I'll take a look.

**Comment by TeXnicians** [comment] 2019-02-22 05:39
@toddhd I've encountered the same issue as yours. Resizing window fixes the bounding box.
I have tried to add `update` every time when I load the data. But the bounding box is still wrong after first loading the page.

But I found a fix:
```
  ngAfterViewChecked() {
    this.selectContainer.update();
  }
```
Call `update` as well in `ngAfterViewChecked` then it got fixed. Not sure why but it may give you more hints on this issue. Sorry I cannot reproduce this on StackBlitz.

**Comment by d3lm** [comment] 2019-02-22 10:38
Hmm 🤔I am wondering what's causing this issue. It would be really nice if you guys @toddhd @TeXnicians could reproduce this in a separate very minimal repo. It doesn't necessarily need to be in a StackBlitz, and it could also be just a minimal Angular app. You can then push that to GitHub and I can take a look. What's important here is the scenario so I can try and reproduce this on my own machine with the dev setup, so I can debug the app.

If you manage to do that I can take a look and try to find the root cause and a fix for it. I am really curious what's causing this behavior.

**Comment by toddhd** [comment] 2019-02-22 15:50
Thanks guys. I'm no longer with the company and not working with that code
anymore (Know of any good job leads?) however one thing I'm wondering... I
was using this inside of an Angular Material dialog box. Zhaodong, is your
code inside of a dialog or popup of some sort?

**Comment by TeXnicians** [comment] 2019-02-23 23:33
@toddhd The code is inside of a `MatTree`.
@d3lm sure I will try to build a minimal app if I can reproduce this.

**Comment by d3lm** [comment] 2019-02-24 10:19
Thanks, looking forward to a MVR so I can take a look.

**Comment by TeXnicians** [comment] 2019-02-24 23:28
@d3lm Fortunately, I can even reproduce it on StackBiltz: https://stackblitz.com/edit/angular-rz4cso 
The selectable tree is in the second accordion, when you expand it, and then drag the selection box, you will see the mismatch. Please let me know if you can see it.

**Comment by d3lm** [comment] 2019-02-25 11:01
@TeXnicians This is not an issue with the library. The problem here is that the select-container as well as the select-items are inside an accordion which means that there are changes to the DOM that the library is not aware of. That is, when the accordion is being expanded, the positions and bounding boxes change, as the browser performs recalculations so that it can correctly render every element on the page.

This is something that the lib should not watch for automatically as there are too many use cases and it would just blow up the library and make it unnecessarily complex.

You can fix this issue by calling `container.update()` once it has expanded and the animation is finished.

So you can do:

```
<mat-expansion-panel (opened)="panelOpenState = true"
  (closed)="panelOpenState = false"
  (afterExpand)="selectContainer.update()">
  ...
</mat-expansion-panel>
```

So in particular the `afterExpand` is important here. That tells you exactly when the accordion's body animation is finished so you can do whatever has to be done. In this case, telling the select-container to update and re-calculate the bounding boxes.

**Comment by TeXnicians** [comment] 2019-02-26 08:40
@d3lm Thanks! This fix works!

**Comment by d3lm** [comment] 2019-02-26 14:13
Happy it worked. I will close this for now and if the issue comes up again, we can either reopen this issue or open a new one.

**Closed by d3lm** 2019-02-26 14:13 UTC
